"""Develop User model

Revision ID: 1e34265dbb79
Revises: 380bdd8dbfc3
Create Date: 2026-01-11 16:25:52.493842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e34265dbb79'
down_revision = '380bdd8dbfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('cover_photo_url')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
